agent:
  hidden_size: 16

train:
  squash:
    nb_generations: 100
    population_size: 40
    percentage_to_keep: 20
    mutation_rate: 0.07
    mutation_scale: 0.05
    mutation_rate_decay: 0.99
    nb_episodes_per_agent: 15
    nb_of_great_players: 10

  target:
    nb_generations: 100
    population_size: 20
    percentage_to_keep: 20
    mutation_rate: 0.1
    mutation_scale: 0.05
    mutation_rate_decay: 0.85
    nb_episodes_per_agent: 25
    nb_of_great_players: 4

  movingtarget:
    nb_generations: 40
    population_size: 50
    percentage_to_keep: 20
    mutation_rate: 0.1
    mutation_scale: 0.3
    mutation_rate_decay: 0.85
    nb_episodes_per_agent: 12
    nb_of_great_players: 5
  

rewards:
  ball_hit_player: 100
  ball_hit_target: 200
  ball_missed: -100
  y_dist_reward_factor: 2
  stability_reward: 0
  centered: 0.005


game:
  action_size: 3
  FPS: 100
  screen_width: 800
  screen_height: 600

